import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const { parseUsageCsv, USAGE_CSV_HEADERS } = await import(pathToFileURL(resolve(process.argv[2])).href);
const cells = Array.from({ length: 14 }, (_, i) => String(i));
cells[10] = '보드,"이름"\r\n두 번째 줄';
cells[13] = "'=SUM(1,2)";
const quote = (value) => `"${value.replaceAll('"', '""')}"`;
const header = USAGE_CSV_HEADERS.map(quote).join(',');
const record = cells.map(quote).join(',');
assert.deepEqual(parseUsageCsv('\uFEFF' + header + '\r\n' + record + '\r\n'), [cells]);
assert.deepEqual(parseUsageCsv(header + '\n' + record), [cells]);
assert.deepEqual(parseUsageCsv(header + '\r\n'), []);
assert.deepEqual(parseUsageCsv(header + '\n' + 'a,'.repeat(13)), [[...Array(13).fill('a'), '']]);
assert.throws(() => parseUsageCsv(header + '\n"unterminated'), /닫히지/);
assert.throws(() => parseUsageCsv(header + '\n"a"x'), /따옴표/);
assert.throws(() => parseUsageCsv('unrelated,file\na,b'), /AAC 사용 기록/);
assert.throws(() => parseUsageCsv(header + '\nwrong,count'), /열 개수/);
console.log('PASS: CSV preview preserves BOM, quoted commas/quotes/newlines, Unicode and formula protection; accepts empty exports and rejects malformed or unrelated files');
